export default {
  meEndpoint: '/auth/me',
  loginEndpoint: '/auth',
  registerEndpoint: '/jwt/register',
  storageTokenKeyName: 'accessToken',
  onTokenExpiration: 'refreshToken',
  category: '/category',
  brand: '/brand',
  blog: '/blogs',
  addBlogs: '/blogs/add-posts',
  banner: '/banners/get-banners',
  addBanner: '/banners/add-banner',
  removeBanner: '/banners/removebanner',
  colors: '/colors',
  getColors: '/colors/get-colors',
  updateColors: '/colors/update-color',
  removeColors: '/colors/remove?color_id=',
  sizes: '/sizes',
  addSize: '/sizes/add-sizes',
  product: '/public/product',
  productDetail: '/public/product/product-detail?product_id=',
  orders: '/orders/get-all-order',
}
